name: Optimize map and deploy

on:
  push:
    branches:
      - master

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Aaaaaaaaaaaadventure Slug Replacement Script
        run: |
          sed -i \
          -e 's/{<devlol>\(.*\)}/\/_\/global\/devlol-systems.pages.devlol.org\/vspace-workadv\1/g' \
          -e 's/{<metalab>\(.*\)}/\/_\/global\/metalab.github.io\/maptest\1/g' \
          -e 's/{<realraum>\(.*\)}/\/_\/global\/realraum.github.io\/workadventur3space\1/g' \
          -e 's/{<steyr-werke>\(.*\)}/\/_\/global\/steyr-werke.gitlab.io\/workadventure-stw\1/g' \
          -e 's/{<2d-thueringen>\(.*\)}/\/_\/global\/raw.githubusercontent.com\/jstsmthrgk\/2D-Welt-thueringen\/main\1/g' \
          -e 's/{<jitsiUrl>}/meet.jit.si/g' \
          -e 's/{<apiUrl>}/https:\/\/play.aaaaaaaaaaaadventu.re/g' *.json hbf/*.json

      - name: Optimize map
        uses: thecodingmachine/map-optimizer-action@master

      - name: Bash
        run: |
          ls -al
          git config --global user.email "d.negrier@thecodingmachine.com"
          git config --global user.name "David Négrier"
          git checkout master
          git commit -am "Adding files"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: . # The folder the action should deploy.
          BASE_BRANCH: master

      - name: Bash2
        run: |
          ls -al
