name: Optimize map and deploy

on:
  push:
    branches:
      - master

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install jq and curl
        run: |
          sudo apt-get update
          sudo apt-get install jq curl

      - name: Aaaaaaaaaaaadventure Slug Replacement Script
        run: |
          curl https://aaaaaaaaaaaadventu.re/replace_slugs.jq -o replace_slugs.jq
          for f in *.json hbf/*.json; do tmp=$(mktemp); jq -f replace_slugs.jq "$f" > "$tmp"; mv "$tmp" "$f"; done

      - name: Optimize map
        uses: thecodingmachine/map-optimizer-action@master

      - name: Bash
        run: |
          ls -al
          git config --global user.email "d.negrier@thecodingmachine.com"
          git config --global user.name "David Négrier"
          git checkout master
          git commit -am "Adding files"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: . # The folder the action should deploy.
          BASE_BRANCH: master

      - name: Bash2
        run: |
          ls -al
